# .streamlit/secrets.toml

[connections.snowflake]
account = "LBZSWPT-HFB32569"
user = "DEWELLER"
password = "Zmalqp1111111!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
clinet_session_keep_alive = "TRUE"
